version: "3"

services:
  minecraft-server:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "true"
      TYPE: FORGE
      VERSION: 1.15.2
      MODS_FILE: /extras/MODS.md
      REMOVE_OLD_MODS: "true"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # - data:/data
      - MODS.md:/extras/MODS.md:ro
