version: "3"

services:
  minecraft-server:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      MODS_FILE: "MODS.md"
      MODRINTH_DOWNLOAD_OPTIONAL_DEPENDENCIES: "TRUE"
      MODRINTH_ALLOWED_VERSION_TYPE: "release"
      EULA: "TRUE"
    tty: true
    stdin_open: true
    restart: unless-stopped
