version: '3.8'

services:
  minecraft-server:
    image: itzg/minecraft-server
    environment:
      VERSION: 1.19.4
      EULA: "true"
      TYPE: FABRIC 
      PACKWIZ_URL: https://raw.githubusercontent.com/AlexvZyl/minecraft-modpack/main/modpack/packwiz/pack.toml
    ports:
      - "25565:25565"
    tty: true
    restart: unless-stopped
    volumes:
    - ./data:/data
    - ./ops.json:/data/ops.json

volumes:
  data: {}
