name = "No-Radars"
author = "AlexvZyl @ GitHub"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfc570be9aa1c765280538982e9eb7fce819b1638928d6bb1588bed9f1fc22e8"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
