name = "No-Radars"
author = "Alexander van Zyl"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "919e536904f13f16b216743727f4f539cb1fa48a695eb608a1bbd19b13e882f5"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
