name = "No-Radars"
author = "AlexvZyl @ GitHub"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec80329bfa9752c4b2a42a03c7c78d3931f8292ddadeeb0afb53a470ae7811d1"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
