name = "No-Radars"
author = "AlexvZyl @ GitHub"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2d90e8e37720d8636b9c6a30ae514afe5139bfa04fc02de2a7e6450a5cc3abd"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
