name = "No-Radars"
author = "AlexvZyl @ GitHub"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "463bc12feb3ee9dff8511dd77e42509d5480f88528a03b610646c93eb1d67fbf"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
