name = "No-Radars"
author = "AlexvZyl @ GitHub"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3ab67065edcc81222e8fb5666014dab67f727206848e7e3b9e86be4d4b3fcc1"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
