name = "No-Radars"
author = "AlexvZyl @ GitHub"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7bf0ef95d4288e41388e7adc3ad34ba01158e6bc1d81d33d33f017943a00c9a"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.2"]
