name = "No-Radars"
author = "AlexvZyl @ GitHub"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b7cf9ea3ce809e5fa7ca842c71990ffa0b9f8cca0bdbb3dcb5f9dc0fecda683"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.2"]
