name = "No-Radars"
author = "AlexvZyl @ GitHub"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "601b2869b607ed26b70ce9752acd891341909669d1db4ae5e92a429f0519bd2e"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
