name = "No-Radars"
author = "Alexander van Zyl"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba8841662c7860c921fed298b136163d26a433ba9d7630d334b11871f883b8cc"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.4"]
