name: Tests 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Test server
      shell: bash
      run: ./server/install.sh

    - name: Test client
      shell: bash
      run: ./client/install.sh
