name: Tests 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Test server
      shell: bash
      run: $HOME/server/install.sh
    - name: Test client
      shell: bash
      run: $HOME/client/install.sh
