name: Tests 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    permissions:
      actions: write
      contents: write

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test server
      shell: bash
      run: sudo "$HOME/server/install.sh"
    - name: Test client
      shell: bash
      run: sudo "$HOME/client/install.sh"
